swiftmailer:
    transport:            gmail
    username:             paniermalin01@gmail.com
    password:             Paniermalin76200
    host:                 localhost
    port:                 465
    encryption:           ssl
    auth_mode:            login
    spool:
        type:             memory
    sender_address:       ~
    antiflood:
        threshold:            99
        sleep:                0
    delivery_addresses:   []
    disable_delivery:     ~
    logging:              '%kernel.debug%'
    stream_options:
          ssl:
             allow_self_signed: true
             verify_peer: false
             verify_peer_name: false
    disable_delivery: false
